// Contact-plan compiler: our JSON link schedules -> the two contact-plan formats NASA's
// open DTN implementations load.
//
//   HDTN (NASA Glenn): JSON { "contacts": [ { contact, source, dest, startTime, endTime,
//                      rateBitsPerSec, owlt } ] }, node numbers, seconds (HDTN user guide).
//   ION  (JPL):        ionadmin commands "a contact +start +end from to rate" and
//                      "a range +start +end from to owlt", relative seconds.
//
// Our plans name links (L1, L2, ...). A plan can declare "nodes" (ipn node numbers) and,
// per link, "from"/"to"; without them the links are read as a simple chain 1->2->3->...
// Both target formats take whole seconds for light time; the exact millisecond value is
// kept in the plan and in the simulator. Times are scaled by the plan's "scale" only when
// asked (--scaled), because HDTN and ION should normally see real mission timing.
//
// Usage: node contact-plans/compile.mjs <plan.json> [--hdtn out.json] [--ion out.rc] [--scaled]
import { readFileSync, writeFileSync } from "node:fs";

export function normalize(plan) {
  if (!plan || !Array.isArray(plan.links) || !Array.isArray(plan.contacts)) throw new Error("plan needs links[] and contacts[]");
  const links = plan.links.map((l, i) => (typeof l === "string" ? { id: l, from: i + 1, to: i + 2 } : { ...l }));
  const nodes = plan.nodes || [...new Set(links.flatMap((l) => [l.from, l.to]))].sort((a, b) => a - b).map((n) => ({ ipn: n, name: `node${n}` }));
  const byId = new Map(links.map((l) => [l.id, l]));
  for (const c of plan.contacts) {
    if (!byId.has(c.link)) throw new Error(`contact references unknown link ${c.link}`);
    if (!(c.down_s > c.up_s)) throw new Error(`contact on ${c.link} must end after it starts`);
  }
  for (const l of links) if (!plan.delays?.[l.id]) throw new Error(`no delay for link ${l.id}`);
  return { ...plan, links, nodes, byId };
}

export function toHdtn(plan, { scaled = false } = {}) {
  const p = normalize(plan);
  const k = scaled ? p.scale ?? 1 : 1;
  const contacts = p.contacts.map((c, i) => {
    const l = p.byId.get(c.link);
    const d = p.delays[c.link];
    return {
      contact: i,
      source: l.from,
      dest: l.to,
      startTime: Math.round(c.up_s * k),
      endTime: Math.round(c.down_s * k),
      rateBitsPerSec: c.rate_bps ?? d.rate_bps ?? 100000,
      owlt: Math.max(0, Math.round((d.one_way_ms / 1000) * k)),
    };
  });
  return { contacts };
}

export function toIon(plan, { scaled = false } = {}) {
  const p = normalize(plan);
  const k = scaled ? p.scale ?? 1 : 1;
  const lines = [`# ${p.name}: generated by contact-plans/compile.mjs`, `# ${p.description || ""}`.trimEnd()];
  for (const c of p.contacts) {
    const l = p.byId.get(c.link);
    const d = p.delays[c.link];
    const s = Math.round(c.up_s * k), e = Math.round(c.down_s * k);
    const rateBytes = Math.round((c.rate_bps ?? d.rate_bps ?? 100000) / 8);
    const owlt = Math.max(0, Math.round((d.one_way_ms / 1000) * k));
    lines.push(`a contact +${s} +${e} ${l.from} ${l.to} ${rateBytes}`);
    lines.push(`a range +${s} +${e} ${l.from} ${l.to} ${owlt}`);
  }
  return lines.join("\n") + "\n";
}

// The simulator's shape (transport/sim.mjs) from a plan: per-link delay, the occulted link
// and its window, all compressed by the plan's scale so a run finishes in seconds.
export function toSimPlan(plan, base, { bundles } = {}) {
  const p = normalize(plan);
  const k = p.scale ?? 1;
  const occ = p.occultation;
  const firstLink = p.links[0].id;
  const linkDelayMs = {};
  for (const l of p.links) linkDelayMs[l.id] = Math.max(1, Math.round(p.delays[l.id].one_way_ms * k));
  return {
    ...base,
    name: p.name,
    oneWayMs: linkDelayMs[firstLink],
    linkDelayMs,
    occultation: occ ? { link: occ.link, downMs: Math.round(occ.down_s * 1000 * k), upMs: Math.round(occ.up_s * 1000 * k) } : { link: "none", downMs: 0, upMs: 0 },
    // Spread departures so part of the payload is in flight when the outage starts.
    staggerMs: occ && bundles ? Math.max(base.staggerMs, Math.ceil((occ.down_s * 1000 * k * 1.5) / bundles)) : base.staggerMs,
  };
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/").split("/").pop())) {
  const args = process.argv.slice(2);
  const file = args.find((a) => a.endsWith(".json") && !args[args.indexOf(a) - 1]?.startsWith("--"));
  if (!file) {
    console.log("usage: node contact-plans/compile.mjs <plan.json> [--hdtn out.json] [--ion out.rc] [--scaled]");
    process.exit(0);
  }
  const plan = JSON.parse(readFileSync(file, "utf8"));
  const scaled = args.includes("--scaled");
  const h = args.indexOf("--hdtn"), i = args.indexOf("--ion");
  if (h >= 0) writeFileSync(args[h + 1], JSON.stringify(toHdtn(plan, { scaled }), null, 2) + "\n");
  if (i >= 0) writeFileSync(args[i + 1], toIon(plan, { scaled }));
  if (h < 0 && i < 0) {
    console.log(JSON.stringify(toHdtn(plan, { scaled }), null, 2));
    console.log(toIon(plan, { scaled }));
  }
}
