// Generates spec/test-vectors.json from the reference implementation, using a FIXED test
// key (never use it for anything real) so every value, including Ed25519 signatures, is
// reproducible. test/spec-vectors.test.mjs regenerates and compares, so the spec and the
// code cannot drift apart.
//
//   node spec/vectors.mjs            print
//   node spec/vectors.mjs --write    write spec/test-vectors.json
import { createPrivateKey, createPublicKey } from "node:crypto";
import { writeFileSync } from "node:fs";
import { canonicalize, contentId, sha256hex } from "../agent/lib/canonical.mjs";
import { leafHash, buildTree, proof, verifyProof } from "../agent/lib/merkle.mjs";
import { signRecord, buildManifest, custodyReceipt, deliveryReceipt } from "../agent/lib/receipt.mjs";
import { gapObject } from "../agent/lib/gap.mjs";
import { batchReceipt, batchProof } from "../agent/lib/batch.mjs";

// Ed25519 private key from a fixed 32-byte seed (RFC 8410 PKCS#8 prefix + seed).
export function testKey(seedHex) {
  const der = Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), Buffer.from(seedHex, "hex")]);
  const priv = createPrivateKey({ key: der, format: "der", type: "pkcs8" });
  const pub = createPublicKey(priv).export({ type: "spki", format: "der" }).toString("base64");
  return { priv, pub };
}

export function buildVectors() {
  const source = testKey("01".repeat(32));
  const relay = testKey("02".repeat(32));
  const dest = testKey("03".repeat(32));

  const canonIn = { b: 2, a: { d: [3, { f: 1, e: 0 }], c: "x" } };
  const leaves = ["alpha", "beta", "gamma"].map((s) => leafHash(Buffer.from(s, "utf8")));
  const tree = buildTree(leaves);

  const payload = Buffer.from("test-vector payload: 0123456789abcdef".repeat(4), "utf8");
  const chunks = [];
  for (let i = 0; i < payload.length; i += 64) chunks.push(payload.subarray(i, i + 64));
  const cLeaves = chunks.map((c) => leafHash(c));
  const cTree = buildTree(cLeaves);
  const manifest = signRecord(source, buildManifest({ payloadId: "0xvector-001", chunkCount: chunks.length, root: cTree.root, meta: { chunkSize: 64 } }));
  const bundleId = contentId({ payloadId: "0xvector-001", index: 1, leafHex: cLeaves[1] });
  const custody = custodyReceipt(relay, { payloadId: "0xvector-001", bundleId, prevHop: "dtn://source/", thisHop: "dtn://relaya/", receivedAt: 1000, forwardedAt: 1050 });
  const gap = gapObject({ link: "L2", linkEvents: [{ link: "L2", event: "down", t: 500 }, { link: "L2", event: "up", t: 2200 }], delayed: [bundleId] });
  const batchIds = [bundleId, contentId({ payloadId: "0xvector-001", index: 0, leafHex: cLeaves[0] }), contentId({ payloadId: "0xvector-001", index: 2, leafHex: cLeaves[2] })];
  const batch = batchReceipt(relay, { prevHop: "dtn://source/", thisHop: "dtn://relaya/", contactId: "vector-contact-1", from: 1000, to: 1100, bundleIds: batchIds });
  const delivery = deliveryReceipt(dest, { payloadId: "0xvector-001", root: cTree.root, rail: "example-rail", network: "example-net", settlementRef: "ab".repeat(32), payTo: "example-payee", amountAtomic: 1000 });

  return {
    note: "Generated by spec/vectors.mjs from the reference implementation. Test keys are derived from the fixed seeds below and must never be used for anything real.",
    keys: { source: { seedHex: "01".repeat(32), pubSpkiB64: source.pub }, relay: { seedHex: "02".repeat(32), pubSpkiB64: relay.pub }, dest: { seedHex: "03".repeat(32), pubSpkiB64: dest.pub } },
    canonical: { input: canonIn, canonical: canonicalize(canonIn), sha256: sha256hex(canonicalize(canonIn)), contentId: contentId(canonIn), contentIdIgnoresCredentials: contentId({ ...canonIn, claimId: "x", sig: "y", signerPub: "z" }) },
    merkle: {
      leavesUtf8: ["alpha", "beta", "gamma"],
      leafHashes: leaves,
      root: tree.root,
      proofIndex2: { index: 2, branch: proof(tree, 2), verifies: verifyProof(leaves[2], proof(tree, 2), 2, tree.root), verifiesAtWrongIndex: verifyProof(leaves[2], proof(tree, 2), 1, tree.root) },
    },
    records: {
      payloadUtf8: payload.toString("utf8"),
      chunkSize: 64,
      manifest,
      custody,
      gap,
      batch: { receipt: batch.receipt, leaves: batch.leaves, proofForCustodyBundle: batchProof(batch, bundleId) },
      delivery,
    },
  };
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, "/").split("/").pop())) {
  const v = buildVectors();
  if (process.argv.includes("--write")) {
    writeFileSync(new URL("./test-vectors.json", import.meta.url), JSON.stringify(v, null, 2) + "\n");
    console.log("wrote spec/test-vectors.json");
  } else console.log(JSON.stringify(v, null, 2));
}
